### ISSUE TITLE
What is the license of these models?

### ISSUE THREAD

**Issue by wangchou** [akirakubo/bert-japanese-aozora#3]
Thanks for sharing models.

[MeCab](https://taku910.github.io/mecab/) is BSD license.
[Sudachi](https://github.com/WorksApplications/Sudachi/blob/develop/LICENSE-2.0.txt) is Apache license.
[unidic-cwj-2.3.0](https://unidic.ninjal.ac.jp/commerce_use) is BSD license.

But [**unidic-qkana_1603**](https://unidic.ninjal.ac.jp/download_all#unidic_qkana) is "CC BY-NC-SA 4.0" license.

So I guess all models are "CC BY-NC-SA 4.0" license?

**Comment by akirakubo** [comment]
The license has not been determined yet.
I think that CC BY-NC-SA 4.0 affects only redistribution of unidic-qkana_1603 itself, but I'm not sure.
We are asking the author of unidic-qkana_1603 about the effect of the license to our models.

**Comment by akirakubo** [comment]
I got a response from the author of unidic-qkana_1603.
They said it's no problem to release our models under Apache License 2.0, same as original BERT models. 
I will update description soon.

**Comment by akirakubo** [comment]
Apache License 2.0 applied.
